import type { UpsertMetricDefinitionInput } from '../../../domain/repositories/metric-definition.repository.js';

// The Metrics Registry's seed catalog — one entry per key in
// metric-calculators.ts. Upserted idempotently at startup (see
// composition-root.ts), so restarting the server never creates duplicates
// and editing this list re-syncs existing rows' metadata.
export const DEFAULT_METRIC_DEFINITIONS: UpsertMetricDefinitionInput[] = [
  {
    key: 'revenue',
    name: 'Revenue',
    description: 'Total revenue recognized across all orders in the selected period.',
    category: 'REVENUE',
    formula: 'SUM(revenue) or SUM(quantity × unit_price) when no revenue column exists',
    unit: 'CURRENCY',
    owner: 'Finance',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'totalOrders',
    name: 'Total Orders',
    description: 'Count of distinct orders placed in the selected period.',
    category: 'REVENUE',
    formula: 'COUNT(DISTINCT order_id)',
    unit: 'COUNT',
    owner: 'Sales Ops',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'averageOrderValue',
    name: 'Average Order Value',
    description: 'Average revenue generated per order.',
    category: 'REVENUE',
    formula: 'Revenue / Total Orders',
    unit: 'CURRENCY',
    owner: 'Sales Ops',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'grossProfit',
    name: 'Gross Profit',
    description: 'Total profit after cost of goods sold.',
    category: 'PROFITABILITY',
    formula: 'SUM(profit) or SUM(revenue − cost) when no profit column exists',
    unit: 'CURRENCY',
    owner: 'Finance',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'profitMargin',
    name: 'Profit Margin',
    description: 'Gross profit expressed as a percentage of revenue.',
    category: 'PROFITABILITY',
    formula: '(Gross Profit / Revenue) × 100',
    unit: 'PERCENTAGE',
    owner: 'Finance',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'repeatPurchaseRate',
    name: 'Repeat Purchase Rate',
    description: 'Percentage of customers who placed more than one order.',
    category: 'CUSTOMER',
    formula: '(Customers with > 1 order / Total customers) × 100',
    unit: 'PERCENTAGE',
    owner: 'Marketing',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'activeCustomers',
    name: 'Active Customers',
    description: 'Count of distinct customers with at least one order in the selected period.',
    category: 'CUSTOMER',
    formula: 'COUNT(DISTINCT customer_id)',
    unit: 'COUNT',
    owner: 'Marketing',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'customerLifetimeValue',
    name: 'Customer Lifetime Value',
    description: 'Average revenue generated per customer.',
    category: 'CUSTOMER',
    formula: 'Revenue / Active Customers',
    unit: 'CURRENCY',
    owner: 'Marketing',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'monthlyGrowthRate',
    name: 'Monthly Growth Rate',
    description: 'Percentage change in revenue between the two most recent months present in the data.',
    category: 'GROWTH',
    formula: '((This Month Revenue − Last Month Revenue) / Last Month Revenue) × 100',
    unit: 'PERCENTAGE',
    owner: 'Executive',
    refreshPolicy: 'REALTIME',
  },
  {
    key: 'inventoryTurnover',
    name: 'Inventory Turnover',
    description: 'How many times inventory is sold and replaced over the selected period.',
    category: 'INVENTORY',
    formula: 'Cost of Goods Sold / Current Inventory Value',
    unit: 'RATIO',
    owner: 'Operations',
    refreshPolicy: 'REALTIME',
  },
];
